version: "3.6"

services:
  # Backend
  backend:
    build:
      context: ../backend
      config: Dockerfile
    ports:
      - "8000:8000"
    restart: always

  # Front-end
  frontend:
    build:
      context: ../frontend
      config: Dockerfile
    ports:
      - "8000:80"
    restart: always

  # MongoDB
  mongo:
    image: "docker.io/library/mongo:6.0.3"
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  # MongoDB Volumes
  mongodb_volume:
